// <auto-generated />
using FairyTale.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FairyTale.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FairyTale.API.Models.Dwarf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SnowWhiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SnowWhiteId");

                    b.ToTable("Dwarfs");
                });

            modelBuilder.Entity("FairyTale.API.Models.SnowWhite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SnowWhites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Белоснежка"
                        });
                });

            modelBuilder.Entity("FairyTale.API.Models.Dwarf", b =>
                {
                    b.HasOne("FairyTale.API.Models.SnowWhite", "SnowWhite")
                        .WithMany("Dwarfs")
                        .HasForeignKey("SnowWhiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SnowWhite");
                });

            modelBuilder.Entity("FairyTale.API.Models.SnowWhite", b =>
                {
                    b.Navigation("Dwarfs");
                });
#pragma warning restore 612, 618
        }
    }
}
